// Auto-generated by scripts/process-bookshelves.js — do not edit by hand.
// To add a bookshelf: drop an image into static/bookshelves/ following the naming
// convention  {university}_{department}_{year}_bookshelf.{ext}  then run npm start.

export interface Bookshelf {
  src: string;
  university: string;
  department: string;
  year: number;
}

export const bookshelves: Bookshelf[] = [
  {
    "src": "/bookshelves/rhul_storyfutures_2023_bookshelf.jpg",
    "university": "Royal Holloway, University of London",
    "department": "StoryFutures",
    "year": 2023
  },
  {
    "src": "/bookshelves/rhul_psychology_2025_bookshelf.jpg",
    "university": "Royal Holloway, University of London",
    "department": "Psychology",
    "year": 2025
  },
  {
    "src": "/bookshelves/rhul_physics_2026_bookshelf.jpg",
    "university": "Royal Holloway, University of London",
    "department": "Physics",
    "year": 2026
  }
];
